### ISSUE TITLE
adjust customizer styles based on recent WordPress updates

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/vendd#146]
When the description is not displaying, the `?` is pretty bare. I'm almost positive it used to have styles. Check on that. 

Collapsed (bad)
![2015-12-12 at 4 55 pm](https://cloud.githubusercontent.com/assets/2359131/11764751/5c3369f6-a0f1-11e5-9e39-191a9d771d75.png)

Expanded (okay)
![2015-12-12 at 4 55-2 pm](https://cloud.githubusercontent.com/assets/2359131/11764754/69a103be-a0f1-11e5-8fa1-c3370d41ab49.png)

**Comment by SDavisMedia** [comment]
Section descriptions need adjustments now too. 

```css
#customize-controls #customize-theme-controls .customize-section-description { margin-top: 10px; }
```
