### ISSUE TITLE
fix incomplete flexbox code for image galleries

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/vendd#164]
Missing gallery item CSS for flexbox. Gallery grids break in Firefox. Needs:

```css
.gallery-item {
	-webkit-justify-content: space-between;
	justify-content: space-between;
	-webkit-flex-flow: column;
	flex-flow: column;
}
```
