### ISSUE TITLE
Add styles for new Stripe card management

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/vendd#201]
https://github.com/easydigitaldownloads/edd-stripe/issues/193

```css
#edd-stripe-manage-cards {
	margin-top: 20px;
	background: #fafafa;
	padding: 30px;
}
```
